/* GENERATED by build-jsx.js from baw.jsx — do not edit this file.
   Edit baw.jsx and re-run: node build-jsx.js */
/* ════════════════════════════════════════════════════════════
   baw.jsx — immersive case page for BAW Clothing.
   The page wears BAW's skin: every value below is sampled from
   the shipped screens (baw-1…5.png) — annotated per token.
   Full-bleed bands via body.baw-mode; the shipped screens are the
   centerpiece, composed big in their real device frames.
   Registers LAYOUTS["baw-case"] → hash route #/baw (app.jsx).
   ════════════════════════════════════════════════════════════ */

const {
  useState: useStateBaw,
  useEffect: useEffectBaw
} = React;

/* ── BAW identity — sampled, not invented ──
   ink        #0d0d0d  (title/logotype, sampled baw-2 PDP capture)
   chalk      #f1f1f1  (panel surface, sampled baw-2)
   concrete   #e8e8e8  (page floor behind photography, sampled baw-2/baw-5)
   buy green  #64d987  (COMPRAR band, sampled baw-2)
   alert pink #ff0f54  ("ÚLTIMAS 13 UNIDADES", sampled baw-2)
   sale purple#9046d9  (SALE nav item, sampled baw-2)
   colorways  #000000 #cdc9c9 #303063 #336676 #b0d6cf #a68aa6 #f29ba4
              (PDP swatch column, sampled baw-3)
   radius     0 — the storefront is squared throughout; only the
              colorway swatches are circles.
   type       heavy grotesque display (Baw® logotype / headings) +
              geometric sans body — neither is web-licensed here, so
              stacks declare the brand face first and fall back:
              "Helvetica Now Display" → Archivo · "Futura PT" → DM Sans. */

const __BAW_STYLE = `
  /* free the page from the constrained canvas — full-bleed bands */
  body.baw-mode .canvas { max-width: none !important; padding: 0 !important; margin: 0 !important; }
  /* a transformed ancestor would hijack the rail's position:fixed */
  body.baw-mode .page-enter { animation: none !important; }
  body.baw-mode .atmosphere, body.baw-mode .grain { display: none; }
  body.baw-mode { background: #e8e8e8; /* concrete — page floor, sampled baw-2 */ }

  body.baw-mode .topbar > * { position: relative; z-index: 1; }
  body.baw-mode .topbar .logo { color: #0d0d0d; transition: color .3s ease; }
  body.baw-mode .nav-link { color: rgba(13,13,13,0.6); transition: color .3s ease; }
  body.baw-mode .nav-link:hover, body.baw-mode .nav-link.active { color: #0d0d0d; }
  body.baw-mode.baw-head-invert .topbar .logo { color: #f1f1f1; }
  body.baw-mode.baw-head-invert .nav-link { color: rgba(241,241,241,0.72); }
  body.baw-mode.baw-head-invert .nav-link:hover,
  body.baw-mode.baw-head-invert .nav-link.active { color: #f1f1f1; }

  .bawx {
    --ink: #0d0d0d;        /* sampled baw-2 · titles + logotype */
    --chalk: #f1f1f1;      /* sampled baw-2 · panel surface */
    --concrete: #e8e8e8;   /* sampled baw-2 · page floor */
    --buy: #64d987;        /* sampled baw-2 · COMPRAR band */
    --alert: #ff0f54;      /* sampled baw-2 · last-units warning */
    --sale: #9046d9;       /* sampled baw-2 · SALE nav item */
    --baw-display: "Helvetica Now Display", "Archivo", system-ui, sans-serif;
    --baw-body: "Futura PT", "DM Sans", system-ui, sans-serif;
    font-family: var(--baw-body); color: var(--ink);
  }

  /* focus is brand-inked and visible everywhere; green ring on dark bands */
  .bawx :focus-visible { outline: 2px solid var(--ink); outline-offset: 2px; }
  .bawx .dark :focus-visible, .bawx .bw-hero :focus-visible { outline-color: var(--buy); }

  /* the left inset clears the fixed rail; the right inset was far smaller, which made
     every band look pushed against the right edge. both are generous now. */
  .bw-wrap { max-width: 1280px; margin: 0 auto;
    padding: 0 clamp(24px, 9vw, 150px) 0 max(212px, clamp(24px, 15vw, 240px)); }
  @media (max-width: 1100px){ .bw-wrap { padding-left: clamp(24px, 5vw, 72px);
    padding-right: clamp(24px, 5vw, 72px); } }

  /* ── left rail ── */
  .bw-rail { position: fixed; left: 36px; top: 50%; transform: translateY(-50%);
    z-index: 30; display: flex; flex-direction: column; gap: 20px;
    mix-blend-mode: difference; }
  @media (max-width: 1100px){ .bw-rail { display: none; } }
  .bw-rail button { display: flex; align-items: center; gap: 12px; background: none;
    border: none; padding: 0; cursor: pointer; font-family: var(--mono);
    font-size: 10.5px; letter-spacing: 0.18em; text-transform: uppercase;
    color: #fff; opacity: .8; transition: opacity .2s ease; }
  .bw-rail button:hover { opacity: 1; }
  .bw-rail button::before { content: ""; width: 22px; height: 1.5px; background: #fff;
    transition: width .25s var(--ease-out); }
  .bw-rail button:hover::before { width: 40px; }

  /* ── section scaffolding — squared chips, the brand has no rounded corners ── */
  .bw-sec { padding: 96px 0 110px; }
  .bw-sec.chalk { background: var(--chalk); }
  .bw-sec.concrete { background: var(--concrete); }
  .bw-sec.dark { background: var(--ink); color: var(--chalk); }
  .bw-chip { display: inline-block; font-family: var(--mono); font-size: 11px;
    letter-spacing: 0.22em; text-transform: uppercase; color: inherit;
    border: 1px solid currentColor; padding: 8px 14px; margin-bottom: 30px; opacity: .85; }
  .bw-count { font-family: var(--mono); font-size: 10px; letter-spacing: 0.1em;
    background: var(--ink); color: var(--chalk); padding: 8px 14px; margin-left: 12px;
    display: inline-block; vertical-align: baseline; margin-bottom: 30px; }
  .bw-h2 { font-family: var(--baw-display); font-weight: 900; letter-spacing: -0.02em;
    text-transform: uppercase; font-size: clamp(40px, 7vw, 100px); line-height: 0.94;
    margin: 0 0 28px; max-width: 15ch; }
  .bw-lede { font-size: clamp(16px, 1.6vw, 20px); line-height: 1.6; max-width: 56ch;
    margin: 0 0 54px; opacity: .85; }

  /* ── hero — the brand's boldest surface: ink + ghost display type ── */
  .bw-hero { position: relative; background: var(--ink); color: var(--chalk);
    overflow: hidden; padding: 150px 0 96px; }
  .bw-ghost { position: absolute; top: 90px; left: 0; white-space: nowrap;
    font-family: var(--baw-display); font-weight: 900; text-transform: uppercase;
    font-size: clamp(120px, 24vw, 340px); line-height: 1; letter-spacing: -0.02em;
    color: rgba(241,241,241,0.05); pointer-events: none; user-select: none;
    display: flex; width: max-content; animation: bawGhost 60s linear infinite; }
  @keyframes bawGhost { to { transform: translateX(-50%); } }
  .bw-hero .bw-wrap { position: relative; }
  .bw-back { font-family: var(--mono); font-size: 10.5px; letter-spacing: 0.14em;
    text-transform: uppercase; color: var(--chalk); background: rgba(241,241,241,0.08);
    border: 1px solid rgba(241,241,241,0.4); padding: 9px 16px; cursor: pointer;
    margin-bottom: 44px; transition: background .2s ease; }
  .bw-back:hover { background: rgba(241,241,241,0.2); }
  .bw-eyebrow { font-family: var(--mono); font-size: 11.5px; letter-spacing: 0.32em;
    text-transform: uppercase; color: var(--buy); margin-bottom: 30px; }
  /* the highlight uses box-shadow, not padding, to gain its side bleed: padding on an
     inline box grows that line's height and nothing else, which is exactly the
     inconsistent leading this title had. with zero padding every line measures the same. */
  .bw-h1 { font-family: var(--baw-display); font-weight: 900; letter-spacing: -0.025em;
    text-transform: uppercase; font-size: clamp(38px, 6.4vw, 104px); line-height: 1.04;
    margin: 0 0 42px; max-width: 12ch; }
  .bw-h1 .noise { background: var(--chalk); color: var(--ink); padding: 0;
    box-shadow: 0.1em 0 0 var(--chalk), -0.08em 0 0 var(--chalk);
    box-decoration-break: clone; -webkit-box-decoration-break: clone; }
  .bw-hero-sub { font-size: clamp(17px, 1.8vw, 21px); line-height: 1.55;
    color: rgba(241,241,241,0.85); max-width: 54ch; margin: 0 0 44px; }
  /* hero CTA — same component as the PDP's COMPRAR band: a marquee in a green rectangle */
  /* now an <a> to the live store: same green band, undecorated */
  .bw-cta { position: relative; display: inline-block; vertical-align: middle;
    width: min(420px, 100%); height: 58px; background: var(--buy); border: none;
    cursor: pointer; overflow: hidden; text-decoration: none;
    transition: transform .2s var(--ease-out); }
  .bw-cta:hover { transform: translateY(-2px); }
  .bw-cta:active { transform: scale(0.99); }
  .bw-cta .track { position: absolute; inset: 0; display: flex; align-items: center;
    white-space: nowrap; width: max-content; animation: bawTicker 14s linear infinite; }
  .bw-cta .track span { font-family: var(--baw-display); font-weight: 900; font-size: 19px;
    letter-spacing: 0.18em; text-transform: uppercase; color: var(--ink); padding: 0 26px; }
  .bw-hero-actions { display: flex; align-items: center; gap: 24px; flex-wrap: wrap; }
  .bw-hero-meta { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 40px; }
  .bw-hero-chip { font-family: var(--mono); font-size: 10.5px; padding: 7px 14px;
    border: 1px solid rgba(241,241,241,0.35); color: rgba(241,241,241,0.85); }
  .bw-hero-chip b { color: var(--chalk); font-weight: 700; text-transform: uppercase;
    letter-spacing: 0.1em; font-size: 9px; margin-right: 6px; }
  /* the COMPRAR band's ticker still drives the hero cta */
  @keyframes bawTicker { to { transform: translateX(-50%); } }

  /* ── screens — the UI showcase: everything visible, composed big ── */
  .bw-wide { max-width: 1760px; margin: 0 auto;
    padding: 0 clamp(16px, 3vw, 48px); display: flex; flex-direction: column;
    gap: clamp(40px, 6vw, 88px); }
  /* the section rail is position:fixed at the viewport's left edge and only
     exists above 1100px, so wide media has to start clear of it instead of
     running underneath the labels */
  @media (min-width: 1101px) { .bw-wide { padding-left: 212px; } }
  .bw-shot { border: 1.5px solid var(--ink); overflow: hidden; line-height: 0;
    background: var(--concrete); }
  .bw-shot.bare { border: none; background: transparent; }
  .bw-shot img { width: 100%; height: auto; display: block; }
  .bw-cap { font-family: var(--mono); font-size: 10px; letter-spacing: 0.16em;
    text-transform: uppercase; opacity: .6; line-height: 1.6; padding: 14px 2px 0;
    text-align: center; }
  .bw-duo { display: grid; grid-template-columns: 1fr 1fr; gap: clamp(20px, 4vw, 56px);
    max-width: 980px; margin: 0 auto; width: 100%; }
  @media (max-width: 640px){ .bw-duo { grid-template-columns: 1fr; } }

  /* ── screens, take two — full-bleed bands, same configuration as the manyfest
     case (.mnf-full): each capture runs the full viewport, the band's own left
     padding clears the fixed rail, and the band's background is sampled from
     that capture's own canvas so there's no seam between page and photo. ── */
  .bw-full { margin-top: 12px; margin-bottom: 0;
    padding: 0;
    padding-left: max(212px, clamp(24px, 15vw, 240px));
    margin-left: calc(-1 * (max((100vw - 1280px) / 2, 0px) + max(212px, clamp(24px, 15vw, 240px))));
    margin-right: calc(-1 * (max((100vw - 1280px) / 2, 0px) + clamp(24px, 9vw, 150px))); }
  .bw-full + .bw-full { margin-top: 0; }
  @media (max-width: 1100px){ .bw-full { padding-left: 0;
    margin-left: calc(-1 * clamp(24px, 5vw, 72px));
    margin-right: calc(-1 * clamp(24px, 5vw, 72px)); } }
  /* sized down to fit a desktop viewport: these are 3D device-mockup renders
     (roughly 4:3), not wide screenshots, so full width alone made them taller
     than the viewport. capping height and letting width follow keeps them
     centered inside the full-bleed band instead of forcing a giant scroll. */
  .bw-full img { display: block; width: auto; height: auto;
    max-width: 100%; max-height: min(640px, 68vh); margin: 0 auto; border: 0; }

  /* ── process — double diamond, four beats ── */
  .bw-process { display: grid; grid-template-columns: repeat(4, 1fr); gap: 22px; }
  @media (max-width: 960px){ .bw-process { grid-template-columns: repeat(2, 1fr); } }
  @media (max-width: 560px){ .bw-process { grid-template-columns: 1fr; } }
  .bw-phase { border-top: 2.5px solid var(--ink); padding-top: 18px; }
  .bw-phase .k { font-family: var(--mono); font-size: 9.5px; letter-spacing: 0.2em;
    text-transform: uppercase; opacity: .55; margin-bottom: 10px; }
  .bw-phase h4 { font-family: var(--baw-display); font-weight: 900; text-transform: uppercase;
    font-size: 19px; letter-spacing: -0.01em; margin: 0 0 10px; }
  .bw-phase p { font-size: 14px; line-height: 1.62; margin: 0; opacity: .78; }

  /* ── decisions (dark band) ── */
  .bw-decisions { display: flex; flex-direction: column; margin-bottom: 72px; }
  .bw-decision { display: grid; grid-template-columns: 90px 1fr; gap: 0 32px;
    padding: 34px 0; border-top: 1.5px solid rgba(241,241,241,0.25); }
  .bw-decision:last-child { border-bottom: 1.5px solid rgba(241,241,241,0.25); }
  .bw-dec-num { font-family: var(--baw-display); font-weight: 900; letter-spacing: -0.04em;
    font-size: clamp(40px, 5vw, 68px); line-height: 1; color: rgba(241,241,241,0.16);
    user-select: none; padding-top: 4px; }
  .bw-dec-title { font-family: var(--baw-display); font-weight: 900; text-transform: uppercase;
    font-size: clamp(17px, 2vw, 22px); margin: 0 0 12px; line-height: 1.2; letter-spacing: -0.005em; }
  .bw-dec-p { font-size: 15px; line-height: 1.68; margin: 0; opacity: .8; }
  @media (max-width: 560px){ .bw-decision { grid-template-columns: 48px 1fr; gap: 0 20px; } }
  .bw-own { display: grid; grid-template-columns: repeat(3, 1fr); gap: 26px 24px; margin-bottom: 28px; }
  @media (max-width: 860px){ .bw-own { grid-template-columns: repeat(2, 1fr); } }
  @media (max-width: 560px){ .bw-own { grid-template-columns: 1fr; } }
  .bw-own-item { border-top: 2.5px solid var(--buy); padding-top: 16px; }
  .bw-own-item h4 { font-family: var(--baw-display); font-weight: 900; text-transform: uppercase;
    font-size: 15px; margin: 0 0 8px; }
  .bw-own-item p { font-size: 14px; line-height: 1.6; margin: 0; opacity: .75; }
  .bw-collab { font-family: var(--mono); font-size: 11.5px; opacity: .6;
    margin: 0; line-height: 1.7; max-width: none; }

  /* portfolio footer on the dark band */
  .bw-sec.dark .pf-label { color: rgba(241,241,241,0.55); }
  .bw-sec.dark .pf-next-link { color: var(--chalk); }
  .bw-sec.dark .pf-next-link:hover { color: var(--buy); }
  .bw-sec.dark .pf-pill { background: transparent; color: var(--chalk);
    border-color: rgba(241,241,241,0.35); }
  .bw-sec.dark .pf-pill:hover { color: var(--buy); border-color: var(--buy); }

  /* motion asks permission — every animation on this page is transform-only */
  @media (prefers-reduced-motion: reduce) {
    .bw-ghost, .bw-cta .track { animation: none !important; }
    .bawx * { transition-duration: 0.01ms !important; }
  }
`;
const BAW_DECISIONS = [{
  title: "Break the rhythm, keep the usability",
  body: "BAW's identity is interruption: oversized ghost headlines bleeding off-canvas, marquee bands, photography that shoves the UI aside. The rule that made it shippable: layout can break rhythm, but never affordance. Prices, sizes, and the buy action sit exactly where a shopper's hand expects them, on every breakpoint. The chaos is art-directed; the commerce is boring on purpose."
}, {
  title: "Color stays neutral at rest, assertive on interaction",
  body: "The whole interface lives in ink on chalk and concrete, sampled straight from the shipped screens. Green (#64D987) exists for exactly one job: buy. Pink (#FF0F54) for scarcity. Purple (#9046D9) for SALE. Because chrome never competes, the street photography and the product do all the shouting, and the three accents read as commands instead of decoration."
}, {
  title: "The buy button is a marquee",
  body: "COMPRAR scrolls inside its own band. The loudest element on the PDP is also the most conventional one: a full-width green rectangle exactly where conversion patterns say it should be. Brand expression and e-commerce orthodoxy in the same 58 pixels. It's the project's thesis in one component."
}, {
  title: "Carry the brand all the way through checkout",
  body: "Most VTEX stores drop to the default checkout at the exact moment money changes hands. We customized the VTEX checkout so type, color, and tone survive payment. They're the riskiest screens to touch and the most valuable, because brand trust matters most when a card number is being typed."
}, {
  title: "Validate navigation before drawing screens",
  body: "A complete navigation workflow (category tree, filters, search behavior) was mapped and validated with the client before high-fidelity design started. With 1,000+ products live, information architecture was the real conversion surface; the homepage concepts came second."
}];
const BAW_OWN = [{
  h: "PDP + PLP design",
  p: "Product detail and listing pages, mobile and desktop: colorway picker, size row, buy band, scarcity messaging."
}, {
  h: "Navigation workflow",
  p: "Category tree, mega menu, search and filter behavior, mapped and validated with the client before hi-fi."
}, {
  h: "Homepage concepts",
  p: "Concept directions for the ghost-type + photography language, iterated with the lead designer."
}, {
  h: "VTEX checkout skin",
  p: "The customized checkout flow that keeps BAW's type and color through payment."
}, {
  h: "Responsive system",
  p: "One layout language across breakpoints: same affordances, different noise levels."
}, {
  h: "Discovery artifacts",
  p: "Workshop facilitation support and the business model canvas that framed scope."
}];
function BawScrollTo(id) {
  const el = document.getElementById(id);
  if (el) el.scrollIntoView({
    behavior: "smooth",
    block: "start"
  });
}
function BawCase({
  spec,
  onAsk
}) {
  const p = typeof PROJECTS !== "undefined" && PROJECTS.baw || {};
  useEffectBaw(() => {
    document.body.classList.add("baw-mode");
    /* header items invert while the ink bands pass underneath */
    const onScroll = () => {
      const y = 46;
      let invert = false;
      for (const s of document.querySelectorAll(".bw-hero, .bw-sec")) {
        const r = s.getBoundingClientRect();
        if (r.top <= y && r.bottom >= y) {
          invert = s.classList.contains("dark") || s.classList.contains("bw-hero");
          break;
        }
      }
      document.body.classList.toggle("baw-head-invert", invert);
    };
    window.addEventListener("scroll", onScroll, {
      passive: true
    });
    onScroll();
    return () => {
      window.removeEventListener("scroll", onScroll);
      document.body.classList.remove("baw-mode", "baw-head-invert");
    };
  }, []);
  return /*#__PURE__*/React.createElement("div", {
    className: "bawx"
  }, /*#__PURE__*/React.createElement("style", null, __BAW_STYLE), /*#__PURE__*/React.createElement("nav", {
    className: "bw-rail",
    "aria-label": "sections"
  }, /*#__PURE__*/React.createElement("button", {
    onClick: () => BawScrollTo("bw-top")
  }, "overview"), /*#__PURE__*/React.createElement("button", {
    onClick: () => BawScrollTo("bw-screens")
  }, "screens"), /*#__PURE__*/React.createElement("button", {
    onClick: () => BawScrollTo("bw-process")
  }, "process"), /*#__PURE__*/React.createElement("button", {
    onClick: () => BawScrollTo("bw-decisions")
  }, "decisions")), /*#__PURE__*/React.createElement("header", {
    className: "bw-hero",
    id: "bw-top"
  }, /*#__PURE__*/React.createElement("div", {
    className: "bw-ghost"
  }, [0, 1].map(half => /*#__PURE__*/React.createElement("span", {
    key: half,
    style: {
      paddingRight: "0.5em"
    }
  }, "WE MAKE NOISE NOT FASHION\xA0★\xA0"))), /*#__PURE__*/React.createElement("div", {
    className: "bw-wrap"
  }, /*#__PURE__*/React.createElement("button", {
    className: "bw-back",
    onClick: () => onAsk && onAsk("show me your work")
  }, "← back to work"), /*#__PURE__*/React.createElement("div", {
    className: "bw-eyebrow"
  }, "baw clothing · studio brizza · 2024"), /*#__PURE__*/React.createElement("h1", {
    className: "bw-h1"
  }, "We make ", /*#__PURE__*/React.createElement("span", {
    className: "noise"
  }, "noise,"), " not fashion."), /*#__PURE__*/React.createElement("p", {
    className: "bw-hero-sub"
  }, "BAW is one of Brazil's loudest streetwear brands, and loud design usually costs conversion. The brief was to keep both: an e-commerce experience unmistakably BAW, disciplined enough to sell, all the way through a customized VTEX checkout."), /*#__PURE__*/React.createElement("div", {
    className: "bw-hero-actions"
  }, /*#__PURE__*/React.createElement("a", {
    className: "bw-cta",
    href: p.liveUrl || "https://www.bawclothing.com.br/",
    target: "_blank",
    rel: "noopener noreferrer",
    "aria-label": "open the live baw store"
  }, /*#__PURE__*/React.createElement("span", {
    className: "track",
    "aria-hidden": "true"
  }, Array.from({
    length: 6
  }).map((_, i) => /*#__PURE__*/React.createElement("span", {
    key: i
  }, "Enter the live store ↗"))))))), /*#__PURE__*/React.createElement("section", {
    className: "bw-sec concrete",
    id: "bw-screens"
  }, /*#__PURE__*/React.createElement("div", {
    className: "bw-wrap"
  }, /*#__PURE__*/React.createElement("span", {
    className: "bw-chip"
  }, "the screens · 01"), /*#__PURE__*/React.createElement("span", {
    className: "bw-count"
  }, "6 captures"), /*#__PURE__*/React.createElement("h2", {
    className: "bw-h2"
  }, "Loud, and it still converts."), /*#__PURE__*/React.createElement("p", {
    className: "bw-lede"
  }, "Every image below is the shipped product: mobile and desktop, framed as captured. Street photography carries the noise; the UI stays ink-on-chalk so the products and the pictures do the talking.")), /*#__PURE__*/React.createElement("div", {
    className: "bw-wrap"
  }, /*#__PURE__*/React.createElement("figure", {
    className: "bw-full",
    style: {
      background: "#eeefe9"
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: "images-baw/BAW1.jpg",
    alt: "BAW homepage, full desktop scroll composed in two panes: the street-photography hero carousel with the 'we make noise not fashion' slogan bands, then the calçados and novidades carousels down to the footer",
    loading: "lazy",
    width: "2600",
    height: "1172"
  })), /*#__PURE__*/React.createElement("figure", {
    className: "bw-full",
    style: {
      background: "#b6a2dd"
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: "images-baw/baw2.jpg",
    alt: "Two tilted mobile screens in phone frames: the search overlay with autocomplete suggestions and a product results grid, overlapping the street-photography home hero reading 'we make noise not fashion' with the cart drawer and checkout total open on top, on a lavender background",
    loading: "lazy",
    width: "2400",
    height: "1800"
  })), /*#__PURE__*/React.createElement("figure", {
    className: "bw-full",
    style: {
      background: "#282828"
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: "images-baw/BAW3.jpg?v=2",
    alt: "Three mobile screens in phone frames on a charcoal background: the street-photography home hero reading 'we make noise not fashion', the camisetas category page with a 1032-product grid and discount tags, and a t-shirt product page with colorway swatches",
    loading: "lazy",
    width: "1200",
    height: "900"
  })), /*#__PURE__*/React.createElement("figure", {
    className: "bw-full",
    style: {
      background: "#d6d7d2"
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: "images-baw/BAW4.jpg",
    alt: "Two desktop pages overlapped: a homepage grid of street-style lookbook tiles with discount tags, and in front, a cropped t-shirt product page with color swatches, size row and a payment info panel",
    loading: "lazy",
    width: "2600",
    height: "1950"
  })), /*#__PURE__*/React.createElement("figure", {
    className: "bw-full",
    style: {
      background: "#282828"
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: "images-baw/BAW5.jpg",
    alt: "Two mobile screens in phone frames: the cart drawer with the green comprar band, and the search overlay with autocomplete suggestions",
    loading: "lazy",
    width: "2000",
    height: "1500"
  })), /*#__PURE__*/React.createElement("figure", {
    className: "bw-full",
    style: {
      background: "#a995da"
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: "images-baw/BAW6.jpg",
    alt: "Two mobile screens in phone frames: a product page with size row and colorway swatches, and the 'você pode gostar' recommendations feeding into the newsletter signup",
    loading: "lazy",
    width: "2000",
    height: "1500"
  })))), /*#__PURE__*/React.createElement("section", {
    className: "bw-sec chalk",
    id: "bw-process"
  }, /*#__PURE__*/React.createElement("div", {
    className: "bw-wrap"
  }, /*#__PURE__*/React.createElement("span", {
    className: "bw-chip"
  }, "the process · 02"), /*#__PURE__*/React.createElement("h2", {
    className: "bw-h2"
  }, "Double diamond, three sprints."), /*#__PURE__*/React.createElement("p", {
    className: "bw-lede"
  }, "Studio Brizza ran the engagement on the Double Diamond. Discovery set the business frame, definition locked the navigation before pixels, and everything shipped across mobile and desktop in three sprints, checkout included."), /*#__PURE__*/React.createElement("div", {
    className: "bw-process"
  }, /*#__PURE__*/React.createElement("div", {
    className: "bw-phase"
  }, /*#__PURE__*/React.createElement("div", {
    className: "k"
  }, "discover · 01"), /*#__PURE__*/React.createElement("h4", null, "Workshop + canvas"), /*#__PURE__*/React.createElement("p", null, "Discovery workshop with the BAW team and a business model canvas to frame who buys, why, and where the margin lives, before any screen existed.")), /*#__PURE__*/React.createElement("div", {
    className: "bw-phase"
  }, /*#__PURE__*/React.createElement("div", {
    className: "k"
  }, "define · 02"), /*#__PURE__*/React.createElement("h4", null, "Navigation first"), /*#__PURE__*/React.createElement("p", null, "A complete navigation workflow (category tree, filters, search) mapped and validated with the client. With 1,000+ SKUs, the IA was the conversion surface.")), /*#__PURE__*/React.createElement("div", {
    className: "bw-phase"
  }, /*#__PURE__*/React.createElement("div", {
    className: "k"
  }, "develop · 03"), /*#__PURE__*/React.createElement("h4", null, "Concepts to system"), /*#__PURE__*/React.createElement("p", null, "Homepage concept directions, then the full mobile + desktop layout language: ghost type, marquee bands, ink-on-chalk chrome, photography full-bleed.")), /*#__PURE__*/React.createElement("div", {
    className: "bw-phase"
  }, /*#__PURE__*/React.createElement("div", {
    className: "k"
  }, "deliver · 04"), /*#__PURE__*/React.createElement("h4", null, "Through checkout"), /*#__PURE__*/React.createElement("p", null, "Shipped on VTEX in three sprints, with a customized checkout that carries the brand through payment: the screens most stores leave on default."))))), /*#__PURE__*/React.createElement("section", {
    className: "bw-sec dark",
    id: "bw-decisions"
  }, /*#__PURE__*/React.createElement("div", {
    className: "bw-wrap"
  }, /*#__PURE__*/React.createElement("span", {
    className: "bw-chip"
  }, "the decisions · 03"), /*#__PURE__*/React.createElement("h2", {
    className: "bw-h2"
  }, "Bold where it brands, boring where it sells."), /*#__PURE__*/React.createElement("div", {
    className: "bw-decisions"
  }, BAW_DECISIONS.map((d, i) => /*#__PURE__*/React.createElement("div", {
    className: "bw-decision",
    key: i
  }, /*#__PURE__*/React.createElement("div", {
    className: "bw-dec-num"
  }, String(i + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
    className: "bw-dec-title"
  }, d.title), /*#__PURE__*/React.createElement("p", {
    className: "bw-dec-p"
  }, d.body))))), /*#__PURE__*/React.createElement("span", {
    className: "bw-chip"
  }, "ownership · 04"), /*#__PURE__*/React.createElement("h2", {
    className: "bw-h2",
    style: {
      fontSize: "clamp(32px, 4.5vw, 64px)"
    }
  }, "What I owned."), /*#__PURE__*/React.createElement("div", {
    className: "bw-own"
  }, BAW_OWN.map((f, i) => /*#__PURE__*/React.createElement("div", {
    className: "bw-own-item",
    key: i
  }, /*#__PURE__*/React.createElement("h4", null, f.h), /*#__PURE__*/React.createElement("p", null, f.p)))), /*#__PURE__*/React.createElement("p", {
    className: "bw-collab",
    style: {
      marginBottom: 72
    }
  }, "Built at Studio Brizza with the lead designer, who owned art direction and the brand relationship; VTEX implementation by the studio's engineering partners. I designed alongside: PDP/PLP, navigation, responsive system, and the checkout skin were mine."), /*#__PURE__*/React.createElement(NextProjectFooter, {
    currentId: "baw",
    onAsk: onAsk
  }))));
}
if (typeof LAYOUTS !== "undefined") LAYOUTS["baw-case"] = BawCase;
Object.assign(window, {
  BawCase
});