#!/usr/bin/env node
/* build-jsx.js — precompiles every .jsx in this folder to a plain .js sibling.
   ana.html loads the .js files (fast path). Append ?dev=1 to the URL to load the
   .jsx through Babel in the browser instead, which is the old behavior.
   RUN THIS AFTER EVERY .jsx EDIT:  node build-jsx.js                        */
const babel = require("@babel/core");
const fs = require("fs");
const path = require("path");

const files = fs.readdirSync(__dirname).filter((f) => f.endsWith(".jsx"));
let total = 0;
for (const f of files) {
  const src = fs.readFileSync(path.join(__dirname, f), "utf8");
  const { code } = babel.transformSync(src, {
    presets: [[require("@babel/preset-react"), { runtime: "classic" }]],
    filename: f,
    compact: false,
    comments: true,
    configFile: false,
    babelrc: false,
  });
  const out = f.replace(/\.jsx$/, ".js");
  const banner = "/* GENERATED by build-jsx.js from " + f + " — do not edit this file.\n" +
    "   Edit " + f + " and re-run: node build-jsx.js */\n";
  fs.writeFileSync(path.join(__dirname, out), banner + code);
  total += code.length;
  console.log("  " + f.padEnd(20) + " -> " + out + "  (" + Math.round(code.length / 1024) + "KB)");
}
console.log("compiled " + files.length + " files, " + Math.round(total / 1024) + "KB of plain JS");
