/* ════════════════════════════════════════════════════════════
   data.jsx — projects, mock AI responses, mockCompose()
   no real AI. keyword → PageSpec.
   ════════════════════════════════════════════════════════════ */

const PROJECTS = {
  "weave": {
    name: "weave.",
    platforms: ["saas", "desktop", "mobile"],
    category: "design system",
    year: "2022–25",
    role: "product designer, design systems",
    short: "autodesk's enterprise design system: four products, one token architecture",
    desc: "three years on the core of autodesk's cross-product system. tokens, components, and documentation good enough that teams adopted without asking.",
    company: "autodesk",
    displayName: "autodesk",
    tag: "design system",
    palette: "sage",
    casePreview: true,
    items: [
      { kind: "shot",   label: "autocomplete", caption: "suggested values", src: "weave-autocomplete.png", w: 795, h: 528, pos: "0% 15%", zoom: 1.3 },
      { kind: "tablet", label: "mobile",       caption: "autocad on ipad", src: "weave-ipad.png", w: 900, h: 638, fit: "contain" },
      { kind: "shot",   label: "skeleton",     caption: "components + loading states", src: "weave-skeleton-2.png", w: 2201, h: 1184, pos: "92% 55%", zoom: 2 },
      { kind: "sticker", label: "autocad",     caption: "autocad", src: "badge-acad.png", dy: 62 },
      { kind: "sticker", label: "fusion",      caption: "fusion", src: "badge-fusion.png", dy: 74 },
      { kind: "note",   label: "note",         caption: "three rewrites. worth it." },
    ],
  },
  "panel": {
    name: "panel.",
    platforms: ["desktop"],
    category: "design system",
    year: "2023",
    role: "component owner",
    short: "one panel component, from every divergent custom build across autodesk",
    desc: "collected every custom panel across autodesk and ran a cross-team workshop to define one. shipped docked, floating, and fixed panels with full docs, replacing the one-off builds.",
    company: "autodesk / weave",
    tag: "component",
    palette: "sage",
    case: {
      problem: "Weave had a panel component. Product teams built their own anyway, driven by space constraints, missing guidance, and UI needs the system didn't cover. Fragmentation like that is expensive: duplicated engineering, inconsistent UX, and eroding trust in the system.",
      solution: "Treated the custom builds as research data: collected every panel variant across Autodesk and mapped what each team changed, and why. Ran a cross-team workshop to define one component, then designed the full behavior set: docked, floating, and fixed panels, collapse and expand states, and vertical tabs.",
      outcome: "One flexible panel component, shipped with complete docs in Figma and on the Weave site, replacing the custom implementations. The workshop-first model became the team's template for aligning before building. Policing became partnership.",
    },
    items: [
      { kind: "photo",  label: "headers", caption: "panel header variants", src: "weave-panel.png", w: 2688, h: 1106 },
      { kind: "shot",   label: "tabs",    caption: "vertical tabs", src: "weave-panel-2.png", w: 902, h: 484 },
      { kind: "screen", label: "states",  caption: "docked / floating / fixed" },
      { kind: "note",   label: "note",    caption: "policing became partnership" },
    ],
  },
  "datagrid": {
    name: "data grid.",
    platforms: ["desktop"],
    category: "design system",
    year: "2024",
    role: "component owner",
    short: "the system's most complex component, shipped feature by feature",
    desc: "owned row grouping, master-detail, pagination, sorting, and resizing. researched each mui behavior, mapped it to how autodesk tables really work, and specced every state before code.",
    company: "autodesk / weave",
    tag: "component",
    palette: "teal",
    case: {
      problem: "As Weave moved to an MUI-based architecture, the Data Grid was the highest-priority component: dense, interrelated features that product teams needed urgently and that couldn't be adopted from MUI as-is.",
      solution: "Split the feature set with the team to move in parallel, owning row grouping and selection, master-detail, empty states, pagination, sorting, and resizing. For each: researched the MUI behavior, mapped it against how Autodesk products actually use tables, and specced every state and edge case with prototypes before any code was written.",
      outcome: "A production-ready table system in Figma and Storybook with feature-by-feature documentation. Product teams got one source of truth instead of a library default each team would adapt alone.",
    },
    items: [
      { kind: "photo",  label: "table",    caption: "the data grid", src: "weave-datagrid.png", w: 700, h: 241 },
      { kind: "shot",   label: "paging",   caption: "pagination + scroll", src: "weave-datagrid-2.png", w: 1384, h: 676 },
      { kind: "screen", label: "states",   caption: "grouping + master-detail" },
      { kind: "note",   label: "note",     caption: "figma + storybook, feature by feature" },
    ],
  },
  "autocomplete": {
    name: "autocomplete.",
    platforms: ["desktop"],
    category: "design system",
    year: "2024",
    role: "component owner",
    short: "sometimes the best component is no component at all",
    desc: "the fusion team asked for a component. research showed autocomplete is really a behavior, so i shipped it across text, dropdown, and search inputs: one definition, three surfaces.",
    company: "autodesk / weave",
    tag: "component",
    palette: "clay",
    case: {
      problem: "During the MUI transition, the Fusion team requested an Autocomplete component. The obvious move was to add a new component. The better move required understanding what the team actually needed.",
      solution: "Research showed Autocomplete isn't really a component. It's a behavior that enhances inputs users already have. I shipped it as a behavior added to text inputs, dropdowns, and search inputs, defining three patterns: combo box, autocomplete suggestions, and results menu.",
      outcome: "One behavior definition, three surfaces, every team covered, and no new component to maintain forever. The system stayed leaner, and every product team got the capability, including the ones that never asked.",
    },
    items: [
      { kind: "photo",  label: "suggestions", caption: "autocomplete menu", src: "weave-autocomplete.png", w: 795, h: 528 },
      { kind: "shot",   label: "patterns",    caption: "combo box / suggestions / results" },
      { kind: "note",   label: "note",        caption: "no new component to maintain" },
    ],
  },
  "skeleton": {
    name: "skeleton loader.",
    platforms: ["desktop"],
    category: "design system",
    year: "2022",
    role: "component owner",
    short: "loading is a perception problem before it's a ui problem",
    desc: "grounded in perception research on waiting. defined five skeleton categories and a rule for each wait threshold, shipped as a loading framework plus a component used across product teams.",
    company: "autodesk / weave",
    tag: "component",
    palette: "sand",
    case: {
      problem: "Autodesk products handled loading inconsistently: different indicators, different behaviors, no shared logic. The request was a Skeleton Loader. The opportunity was a principled approach to waiting, for the whole system.",
      solution: "Grounded the work in perception research on waiting, validated by internal and external audits. Defined a taxonomy of five skeleton categories, each with shape, sizing, and behavior rules under one gradient-wave animation, and set the structural principle: keep persistent UI static, skeleton only the content that's actually loading.",
      outcome: "A functional component used by multiple product teams, plus a durable, shared framework for loading decisions across the design system.",
    },
    items: [
      { kind: "photo",  label: "loader",  caption: "determinate progress", src: "weave-skeleton.png", w: 2768, h: 2188 },
      { kind: "shot",   label: "spinner", caption: "indeterminate loader", src: "weave-skeleton-2.png", w: 2201, h: 1184 },
      { kind: "screen", label: "thresholds", caption: "under 1s / 1-9s / over 9s" },
      { kind: "note",   label: "note",    caption: "keep persistent ui static" },
    ],
  },
  "manychat-ds": {
    name: "manyfest.",
    displayName: "manychat",
    platforms: ["desktop", "ios", "android"],
    category: "design system",
    year: "2025–now",
    role: "senior product designer, design systems",
    short: "an AI-native system for three platforms, with agents in the pipeline from day one",
    desc: "the manychat design system, designed for two audiences at once: humans and agents. agents hallucinate; the system is the guardrail.",
    company: "manychat",
    tag: "design system",
    palette: "sky",
    stamp: true,
    items: [
      { kind: "photo",  label: "cover", caption: "manyfest ds", src: "manyfest-cover.png", w: 2000, h: 1144, pos: "12% 38%", zoom: 1.35 },
      { kind: "proto",  label: "mobile", caption: "manyme v.0 · onboarding", src: "manyfest-mobile.png", w: 612, h: 1286 },
      { kind: "shot",   label: "components", caption: "button · 144 variants", src: "manyfest-buttons.png", w: 1616, h: 2048, pos: "45% 12%", zoom: 2.2 },
      { kind: "sticker", label: "manychat", caption: "manychat", dy: 66 },
      { kind: "note",   label: "wip",    caption: "shipping right now" },
      { kind: "photo",  label: "the team", caption: "manyfest night", src: "manyfest-2.jpg", w: 1155, h: 730 },
    ],
  },
  "releve": {
    name: "(r)elevē.",
    platforms: ["web"],
    category: "ai",
    year: "2026",
    role: "designer + engineer",
    short: "ballet correction from video, traced to the syllabus",
    desc: "an elisava capstone by someone with 20 years at the barre. reads 33 body landmarks from video, measures them against rad syllabus ranges, and returns corrections a teacher would endorse, in english and portuguese.",
    company: "elisava",
    tag: "AI",
    tags: ["AI", "pose estimation"],
    palette: "clay",
    items: [
      { kind: "shot",   label: "the app",    caption: "analysis · live corrections", src: "releve-4.jpg", w: 1920, h: 1080, pos: "50% 40%", zoom: 1.15 },
      { kind: "photo",  label: "demo",       caption: "the app, staged", src: "releve-1.jpg", w: 1920, h: 1080, pos: "12% 45%", zoom: 1.2 },
      { kind: "proto",  label: "review",     caption: "correction timeline", src: "releve-m2.png", w: 724, h: 1674 },
      { kind: "proto",  label: "home",       caption: "technique score · streaks", src: "releve-m1.png", w: 712, h: 1706 },
      { kind: "note",   label: "note",       caption: "precision is a form of care" },
      { kind: "wordmark", label: "elisava",  caption: "elisava", src: "elisava.png", dy: 48 },
    ],
  },
  "canal": {
    name: "canal.",
    platforms: ["desktop", "mobile"],
    category: "e-commerce",
    year: "2023",
    role: "product designer, with the lead designer",
    short: "a new brand identity deserved a store to match",
    desc: "women's fashion e-commerce for studio brizza. a business model canvas workshop, homepage concept, full navigation, and mobile and desktop screens across three sprints. live at canal.com.br.",
    company: "canal · studio brizza",
    tag: "e-commerce",
    palette: "rose",
    liveUrl: "https://www.canal.com.br/roupas/casacos",
    case: {
      problem: "Canal is a Brazilian women's fashion brand known for elegant design and quality materials. The brand had evolved; its e-commerce, the brand's highest-traffic touchpoint, hadn't. Every visit widened the credibility gap. The brief: make the store feel like the brand.",
      solution: "Ran a business model canvas workshop to surface motivations, differentiators, and personas, then sketched the homepage, defined the full navigation workflow, and validated the UI with the client before production. The design principle: the product is the point. Large imagery dominates the viewport, a quiet sans-serif steps back beside the brand's bold campaign fonts, and black, white, and gray with square geometry carry the class while the photography carries the boldness.",
      outcome: "The store now speaks the brand's language at its highest-traffic touchpoint, live at canal.com.br. Three sprints from workshop to production.",
    },
    items: [
      { kind: "photo",  label: "mockup", caption: "canal concept", src: "Frame 1000005235.png", w: 1813, h: 1813 },
      { kind: "photo",  label: "store", caption: "canal concept", src: "canal-1.png", w: 1359, h: 2394 },
      { kind: "proto",  label: "nav",   caption: "navigation", src: "canal-2.png", w: 1359, h: 2394 },
      { kind: "proto",  label: "pdp",   caption: "compre junto", src: "canal-3.png", w: 1359, h: 2394 },
      { kind: "shot",   label: "desktop nav", caption: "desktop mega menu", src: "canal-5.png", w: 2013, h: 1350 },
      { kind: "shot",   label: "desktop pdp", caption: "desktop compre junto", src: "canal-6.png", w: 1342, h: 900 },
    ],
  },
  "baw": {
    name: "baw.",
    platforms: ["desktop", "mobile"],
    category: "e-commerce",
    year: "2024",
    role: "product designer, with the lead designer",
    short: "we make noise, not fashion. loud, and it still converts.",
    desc: "streetwear e-commerce with a customized vtex checkout. loud design usually costs conversion; the brief was to have both. mobile and desktop across three sprints, live at bawclothing.com.br.",
    company: "baw clothing · studio brizza",
    tag: "e-commerce",
    palette: "sand",
    liveUrl: "https://www.bawclothing.com.br/",
    case: {
      problem: "BAW is one of Brazil's most recognizable streetwear brands, and loud design usually costs conversion. The challenge: an e-commerce experience unmistakably BAW, disciplined enough to sell, all the way through a customized VTEX checkout.",
      solution: "Followed the Double Diamond, starting with a discovery workshop and business model canvas, then homepage concepts and a complete navigation workflow validated with the client. Delivered mobile and desktop across three sprints, including a customized VTEX checkout that keeps the brand intact through payment. The layout breaks grid rhythm without breaking usability, and color stays neutral at rest, assertive on interaction, so the imagery does the shouting.",
      outcome: "An e-commerce experience that carries BAW's identity from homepage to checkout, live at bawclothing.com.br. Bold where the brand needed it, invisible where conversion demanded it.",
    },
    items: [
      { kind: "photo",  label: "mockup", caption: "baw clothing", src: "Frame 1000005236.png", w: 1578, h: 1578 },
      { kind: "photo",  label: "home",   caption: "we make noise", src: "baw-1.png", w: 1486, h: 1208 },
      { kind: "shot",   label: "pdp",    caption: "product page", src: "baw-2.png", w: 2678, h: 1624 },
      { kind: "proto",  label: "mobile", caption: "moletons", src: "baw-3.png", w: 796, h: 1596 },
      { kind: "proto",  label: "camisetas", caption: "camisetas listing", src: "baw-4.png", w: 796, h: 1596 },
      { kind: "note",   label: "note",   caption: "loud, and still converts" },
    ],
  },
  "espm": {
    name: "espm.",
    platforms: ["mobile"],
    category: "research",
    year: "2021",
    role: "ux/ui designer, with one colleague",
    short: "our graduation project: redesigning the app we used every day",
    desc: "an information-architecture redesign of espm's student app. brand, market, and student research, then a restructured app validated with students before hi-fi.",
    company: "espm",
    tag: "ux/ui",
    palette: "teal",
    case: {
      problem: "ESPM's brand promises innovation and attitude. Its student app delivered neither: hard-to-find information and confusing navigation. As students, we lived the gap daily, so we proposed the redesign as our graduation project.",
      solution: "Grounded it in three layers of research: brand positioning, a market and competitor audit of FAAP, FGV, Insper, and Mackenzie, and a survey of 36 ESPM students. The core was information architecture: we rebuilt the structure around what students actually come to do, putting grades, schedules, and financial info up front and cutting navigation depth everywhere else, with flows validated before high-fidelity screens.",
      outcome: "A validated app concept: restructured architecture tested with students before a single hi-fi screen, putting grades, schedules, and money where students said they live. My first end-to-end project, and the pattern I still follow: research before opinion, architecture before interface.",
    },
    items: [
      { kind: "photo",  label: "mockup",   caption: "espm student app", src: "Frame 1000005225.png", w: 1152, h: 1230 },
      { kind: "photo",  label: "home",     caption: "student app", src: "espm-1.png", w: 934, h: 1860 },
      { kind: "proto",  label: "calendar", caption: "calendar", src: "espm-3.png", w: 934, h: 1860 },
      { kind: "proto",  label: "dashboard", caption: "home dashboard", src: "espm-4.png", w: 934, h: 1860 },
      { kind: "proto",  label: "grades",   caption: "marketing II exams", src: "espm-5.png", w: 934, h: 1860 },
      { kind: "note",   label: "note",     caption: "research before opinion" },
    ],
  },
};

const MOCK_RESPONSES = {
  "full weave case|weave case|full case|weave deep dive|tell me about weave|^weave$": {
    layout: "case-study",
    title: "weave.",
    subtitle: "autodesk / weave",
    intro: "",
    items: ["weave"],
    doodles: [],
  },
  "best project|best work|favou?rite project|favou?rite work|favou?rite one|your best|proudest": {
    layout: "manyfest-case",
    title: "manyfest.",
    subtitle: "manychat design system",
    intro: "",
    items: ["manychat-ds"],
    doodles: [],
  },
  "projects|portfolio|show me your|your work|see your work|selected work|all your|everything you|your projects": {
    layout: "gallery",
    title: "selected work.",
    subtitle: "two design systems, three platforms each, and the work in between",
    intro: "every case page wears its project's skin. dive into each universe, and i'll tell you the messy parts if you ask.",
    items: ["manychat-ds", "weave", "releve", "espm", "canal", "baw"],
    doodles: [],
  },
  "fashion|commerce|e-commerce|ecommerce|retail|shop|store|brizza|fintech|payment|bank|money|finance": {
    layout: "themed-list",
    title: "commerce work.",
    subtitle: "projects · fashion + retail · 2 results",
    intro: "two studio brizza builds: fashion storefronts for canal and baw.",
    items: ["canal", "baw"],
    doodles: [
      { type: "asterisk", text: "studio brizza era", position: { top: "22%", right: "12%" }, rotation: 4 },
    ],
  },
  "good at|strength|quality|superpower|great at|best at": {
    layout: "quality-showcase",
    title: "i think in systems.",
    subtitle: "across two design systems and counting",
    intro: "i can't help it. give me three components and i'll find the missing seven.",
    items: ["weave", "manychat-ds"],
    doodles: [
      { type: "underline", text: "obsessed", position: { top: "17%", left: "16%" }, rotation: -2 },
    ],
  },
  "hate|redo|hard|struggle|worst|regret|mistake": {
    layout: "honest-list",
    title: "things i'd redo.",
    subtitle: "uncomfortable but honest",
    intro: "asked and answered. these keep me up at night.",
    items: [
      { text: "the navigation on canal", project: "canal" },
      { text: "the color tokens in weave v1", project: "weave" },
      { text: "the empty state in baw checkout", project: "baw" },
    ],
    doodles: [
      { type: "note", text: "this one HURTS", position: { top: "44%", right: "6%" }, rotation: -7 },
      { type: "circle", text: "ouch", position: { bottom: "20%", left: "8%" }, rotation: 6 },
    ],
  },
  "elev|ballet|releve": {
    layout: "releve-case",
    title: "(r)elevē.",
    subtitle: "elisava capstone · pose estimation",
    intro: "",
    items: ["releve"],
    doodles: [],
  },
  "manyfest|manychat design system|manychat ds|tell me about manychat": {
    layout: "manyfest-case",
    title: "manyfest.",
    subtitle: "manychat design system",
    intro: "",
    items: ["manychat-ds"],
    doodles: [],
  },
  "tell me about panel|weave panel|^panel$|panel component|data grid|datagrid|autocomplete|skeleton": {
    layout: "case-study",
    title: "weave.",
    subtitle: "autodesk / weave",
    intro: "",
    items: ["weave"],
    doodles: [],
  },
  "tell me about canal|^canal|canal store": {
    layout: "canal-case",
    title: "canal.",
    subtitle: "canal · studio brizza · 2023",
    intro: "a new brand identity deserved a store to match.",
    items: ["canal"],
    doodles: [],
  },
  "tell me about baw|^baw|baw clothing": {
    layout: "baw-case",
    title: "baw.",
    subtitle: "baw clothing · studio brizza · 2024",
    intro: "",
    items: ["baw"],
    doodles: [],
  },
  "tell me about espm|^espm|espm app": {
    layout: "espm-case",
    title: "espm.",
    subtitle: "espm · graduation project · 2021",
    intro: "our graduation project: the app we used every day, rebuilt.",
    items: ["espm"],
    doodles: [],
  },
  "about|who are you|tell me about|yourself|you$": {
    layout: "about",
    title: "ana fellipelli.",
    subtitle: "product designer · são paulo · manychat",
    intro: "born in são paulo. i build design systems that ship across platforms: currently manychat's AI-native system, previously autodesk's weave. i think in systems; i can't help it.",
    doodles: [
      { type: "circle", text: "yes that's me", position: { top: "16%", right: "16%" }, rotation: 5 },
    ],
  },
  "hire|work with|available|open to|contact|reach|talk|email": {
    layout: "contact",
    title: "let's talk.",
    subtitle: "obrigada for reaching out",
    intro: "yes, selectively. tell me what you're building.",
    doodles: [],
  },
};

const OFF_TOPIC = {
  layout: "off-topic",
  title: "off-topic.",
  subtitle: "",
  intro: "",
  big: "that's a great question for someone who is not a portfolio.",
  doodles: [],
};

function mockCompose(question) {
  const q = (question || "").toLowerCase().trim();
  for (const keys in MOCK_RESPONSES) {
    const re = new RegExp(keys, "i");
    if (re.test(q)) {
      return { ...MOCK_RESPONSES[keys], _matched: keys, _question: question };
    }
  }
  return { ...OFF_TOPIC, _matched: "off-topic (no match)", _question: question };
}

const PLACEHOLDER_CYCLE = [
  "what's your best project?",
  "are you open to work?",
  "show me your fintech work",
  "what do you hate doing?",
];

Object.assign(window, { PROJECTS, MOCK_RESPONSES, mockCompose, PLACEHOLDER_CYCLE });
