/* GENERATED by build-jsx.js from doodles.jsx — do not edit this file.
   Edit doodles.jsx and re-run: node build-jsx.js */
/* ════════════════════════════════════════════════════════════
   doodles.jsx — handwritten layer (Caveat + wobbly SVG)
   draws in via stroke-dashoffset; label fades up.
   ════════════════════════════════════════════════════════════ */

const {
  useState,
  useEffect
} = React;

/* each doodle renders its own little SVG mark + Caveat label */
function DoodleMark({
  type,
  text
}) {
  if (type === "arrow") {
    return /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-start",
        gap: 2
      }
    }, /*#__PURE__*/React.createElement("span", {
      className: "label"
    }, text), /*#__PURE__*/React.createElement("svg", {
      width: "96",
      height: "46",
      viewBox: "0 0 96 46"
    }, /*#__PURE__*/React.createElement("path", {
      pathLength: "1",
      d: "M4 6 C 20 2, 44 10, 62 26 C 70 33, 78 38, 86 40"
    }), /*#__PURE__*/React.createElement("path", {
      pathLength: "1",
      d: "M86 40 L 72 39"
    }), /*#__PURE__*/React.createElement("path", {
      pathLength: "1",
      d: "M86 40 L 80 28"
    })));
  }
  if (type === "circle") {
    return /*#__PURE__*/React.createElement("div", {
      style: {
        position: "relative",
        padding: "10px 18px"
      }
    }, /*#__PURE__*/React.createElement("svg", {
      width: "150",
      height: "74",
      viewBox: "0 0 150 74",
      style: {
        position: "absolute",
        inset: 0
      }
    }, /*#__PURE__*/React.createElement("ellipse", {
      pathLength: "1",
      cx: "75",
      cy: "37",
      rx: "70",
      ry: "30",
      transform: "rotate(-4 75 37)"
    })), /*#__PURE__*/React.createElement("span", {
      className: "label",
      style: {
        position: "relative"
      }
    }, text));
  }
  if (type === "underline") {
    return /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 1
      }
    }, /*#__PURE__*/React.createElement("span", {
      className: "label"
    }, text), /*#__PURE__*/React.createElement("svg", {
      width: "110",
      height: "16",
      viewBox: "0 0 110 16"
    }, /*#__PURE__*/React.createElement("path", {
      pathLength: "1",
      d: "M4 9 C 26 4, 52 13, 76 7 C 88 4, 98 8, 106 6"
    })));
  }
  if (type === "asterisk") {
    return /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        alignItems: "center",
        gap: 8
      }
    }, /*#__PURE__*/React.createElement("svg", {
      width: "34",
      height: "34",
      viewBox: "0 0 34 34"
    }, /*#__PURE__*/React.createElement("line", {
      pathLength: "1",
      x1: "17",
      y1: "4",
      x2: "17",
      y2: "30"
    }), /*#__PURE__*/React.createElement("line", {
      pathLength: "1",
      x1: "5",
      y1: "11",
      x2: "29",
      y2: "23"
    }), /*#__PURE__*/React.createElement("line", {
      pathLength: "1",
      x1: "29",
      y1: "11",
      x2: "5",
      y2: "23"
    })), /*#__PURE__*/React.createElement("span", {
      className: "label"
    }, text));
  }
  // note — text only
  return /*#__PURE__*/React.createElement("span", {
    className: "label"
  }, text);
}
function Doodle({
  spec,
  index,
  active
}) {
  const [drawn, setDrawn] = useState(false);
  useEffect(() => {
    if (!active) {
      setDrawn(false);
      return;
    }
    const t = setTimeout(() => setDrawn(true), 150 * index + 60);
    return () => clearTimeout(t);
  }, [active, index]);
  const style = {
    ...spec.position,
    transform: `rotate(${spec.rotation || 0}deg)`
  };
  return /*#__PURE__*/React.createElement("div", {
    className: "doodle" + (drawn ? " drawn" : ""),
    style: style
  }, /*#__PURE__*/React.createElement(DoodleMark, {
    type: spec.type,
    text: spec.text
  }));
}
function DoodleLayer({
  doodles,
  active
}) {
  if (!doodles || !doodles.length) return null;
  return /*#__PURE__*/React.createElement("div", {
    className: "doodle-layer"
  }, doodles.map((d, i) => /*#__PURE__*/React.createElement(Doodle, {
    key: i,
    spec: d,
    index: i,
    active: active
  })));
}
Object.assign(window, {
  Doodle,
  DoodleLayer,
  DoodleMark
});